version: '3.8'
services:
  app:
    image: app100:latest
    ports:
      - "8081"
    depends_on:
      - jaysql

    entrypoint: "/bin/sh -c 'java -jar /app.jar --spring.datasource.url=jdbc:mysql://jaysql/demo?serverTimezone=UTC'"

  jaysql:
    image: mysql:latest
    ports:
      - "3036"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root

  nginx:
     image: nginx:latest
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
       - app

     ports:
       - "4000:4000"

